### ISSUE TITLE
not able to change wardens bug (aka, wrong neighborhood mothafuck bug)

### ISSUE THREAD

**Issue by jimbobrlw** [CardboardKeep/Warden#103]
after unlocking medeira, i tried to swap back to tavian and got this bug
![wrong tree wrong time](https://cloud.githubusercontent.com/assets/12590123/10445575/35e0e978-71c0-11e5-808b-765ae0a761c7.png)

**Comment by Talsidor** [comment]
From Tim's Trello card:
Warden Cloning
ArgumentException: The thing you want to instantiate is null.
UnityEngine.Object.CheckNullArgument (System.Object arg, System.String message) (at C:/buildslave/unity/build/Runtime/Export/UnityEngineObject.cs:102)
UnityEngine.Object.Instantiate (UnityEngine.Object original, Vector3 position, Quaternion rotation) (at C:/buildslave/unity/build/Runtime/Export/UnityEngineObject.cs:79)
NewWeapon.ReconstructWeapon (.WeaponMemento memento) (at Assets/-Warden/Scripts/Entities/ItemsAndCollectables/NewWeapon.cs:401)
Player.LoadInventory () (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:2420)
Player.Awake () (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:137)
UnityEngine.Object:Instantiate(Object, Vector3, Quaternion)
<Shapeshift>c__Iterator2F:MoveNext() (at Assets/-Warden/Scripts/Entities/Wardens/Player.cs:2527)

This error seemed to throw when I managed to produce the Warden cloning bug.
This time I was Medeira trying to turn into Bitt. And after the animation was Meds stuck in the crouching animation. Needed to console tap to regain control.

The same thing happens when going from Tav to Bitt.

This bug is hard to repro, and seems to only happen after transitioning a few times between levels.
To Repro I play through the game start to finish. Before transitioning I try to become every Warden, and after Transitionig I try to become every Warden

**Comment by Talsidor** [comment]
I believe I've discovered the culprit of this and should have both cushioned the bug and had it output an error log giving more info. It's not fixed yet though, and when it happens it'll cause a Warden to not have a weapon they had when you were last them.

**Comment by Talsidor** [comment]
The actual cause behind this has been identified and fixed, plus will replaced with a more reliable system that should never cause it again after PAX.
