### ISSUE TITLE
Standing on edge of Needlenose vision range causes it to spasm.

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#57]
Standing on the edge of the needlenoses vision causes it to spin around to look at the player and spawn the "Alerted" icon.
Standing on the edge causes this to happen repeatedly, causing the NN to look like it is spasming.

Repro:
Approach needle nose from behind. 
Slowly walk towards it.
Atthe very edge of it's vision it will spasm.

**Comment by jimbobrlw** [comment]
looks like the enemy scripts engageupdate had an if statement that would disengage if the NN the lost sight of the player if they got too far behind them.

this code didn't work for the NN because it assumes the enemy can rotate their body, which it cant.
I overrided the EngageUpdate in the NN script and commented out the if statement that checks the players position versus the angle of the NN, works fine now.
