### ISSUE TITLE
CamRig Rewrite Issues.

### ISSUE THREAD

**Issue by Agilethief** [CardboardKeep/Warden#93]
Upon spawn in new scene, main cam starts at world 0,0,0 and zooms to where the player is.
This is quite jarring.

Repro:
Transition from one scene to another.
Observe the main cameras position upon entering the new level.

Note:
Was mainly noticed in the mine levels.

**Comment by jimbobrlw** [comment]
The player slides in the wrong direction, faces the wrong direction after they stop movement input, and faces the wrong direction when their zoning in/out.

seems to be towards 0.0,0.0,0.0,1.0.

The Player seems to be facing up to the camrigs rot but for some reason that rot isn't correct after the player isn't pressing any directional buttons and is always incorrect when they're sliding.

**Comment by jimbobrlw** [comment]
"Agilethief commented 23 minutes ago

Going into first person mode rolls the camera when it should only yaw and pitch the camera.
Feels very odd to use.

Repro:
Any scene.
Go into first person mode.
Look around."

**Comment by jimbobrlw** [comment]
"Agilethief commented 4 days ago

Transition zones appear to cause the Warden to walk to a weird spot.
When walking into a transition zone, the Warden will walk towards the center of the zone, pass it and turn around. (Walking back the way they came instead of further into the zone)

This behaviour looks bad and unpolished.

Repro:
Walk into a transition zone
Observe the movements of the Warden.

Was produced in the mine levels, may be unique to their transition zones (placement perhaps?)"

**Comment by Talsidor** [comment]
I fixed almost all these problems a week or two ago, as they were also on Trello, except the first-person one, which I'll re-open the individual issue for. Issues shouldn't really be merged unless they're describing exactly the same problem. (Unlike Trello Github doesn't have checklists, and as their name suggests each "issue" should be one issue.)
